- .gitignore
- build.gradle
- settings.gradle
- src/main/java/com/encore/thecatch/TheCatchApplication.java
- src/main/resources/application.properties
- src/main/resources/application.yml
- src/test/java/com/encore/thecatch/TheCatchApplicationTests.java
> backend init

- event/build.gradle
- event/src/main/java/com/encore/event/common/UseCase.java
- event/src/main/java/com/encore/event/common/WebAdapter.java
- event/src/main/java/com/encore/event/coupon/adapter/in/web/CouponIssueController.java
- event/src/main/java/com/encore/event/coupon/adapter/out/kafka/KafkaLimitedCouponProducerAdapter.java
- event/src/main/java/com/encore/event/coupon/application/port/in/ApplyForLimitedCouponIssueCommend.java
- event/src/main/java/com/encore/event/coupon/application/port/in/ApplyForLimitedCouponIssueUseCase.java
- event/src/main/java/com/encore/event/coupon/application/port/out/ApplyForLimitedCouponIssueOutPort.java
- event/src/main/java/com/encore/event/coupon/application/service/ApplyForLimitedCouponIssue.java
- event/src/main/java/com/encore/event/healthcheck/adpater/in/web/HealthCheckController.java
#6 
healthcheck 코드 추가
EDD 핵사고날 아키텍처 적용
선착순 쿠폰 카프카로 이벤트 생성 코드 작성
> event kafka 한정쿠폰 이벤트 발행 테스트중

- crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
- crm/src/main/java/com/encore/thecatch/coupon/dto/CouponResDto.java
- crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
> [Feat]Coupon FE 연결중

- crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
- crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
- crm/src/main/java/com/encore/thecatch/common/security/SecurityConfig.java
> [Fix] 관리자 계정 생성 #35

- crm/src/main/java/com/encore/thecatch/admin/repository/AdminQueryRepository.java
- crm/src/main/java/com/encore/thecatch/comments/controller/CommentsController.java
- crm/src/main/java/com/encore/thecatch/comments/entity/Active.java
- crm/src/main/java/com/encore/thecatch/comments/service/CommentsService.java
- crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
- crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
- crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
- crm/src/main/java/com/encore/thecatch/user/controller/UserController.java
- crm/src/main/java/com/encore/thecatch/user/dto/response/ChartAgeRes.java
- crm/src/main/java/com/encore/thecatch/user/dto/response/ChartGenderRes.java
- crm/src/main/java/com/encore/thecatch/user/dto/response/ChartGradeRes.java
- crm/src/main/java/com/encore/thecatch/user/repository/UserQueryRepository.java
- crm/src/main/java/com/encore/thecatch/user/service/UserService.java
> * #36 
- 성별 통계로직 구현
- 나이대 통계 로직 구현
- 회원 등급 통계 로직 구현
> [Feat] 통계데이터 조회 로직 구현 #36

- crm/src/main/java/com/encore/thecatch/comments/service/CommentsService.java
- crm/src/main/java/com/encore/thecatch/common/security/SecurityConfig.java
- crm/src/main/java/com/encore/thecatch/complaint/controller/ComplaintController.java
- crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
- crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintRepository.java
- crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
- crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
> 고객리스트 로직 수정 (#47)

- crm/src/main/java/com/encore/thecatch/admin/dto/response/AdminInfoResDto.java
- crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
> [Fix] findByAdminId 수정

- crm/src/main/java/com/encore/thecatch/publishcoupon/kafka/CouponKafkaEventListener.java
- crm/src/main/java/com/encore/thecatch/receivecoupon/kafka/CouponKafkaEventListener.java
> [Feat] Push알림 구현 수정5

- crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
- crm/src/main/java/com/encore/thecatch/admin/domain/Admin.java
- crm/src/main/java/com/encore/thecatch/admin/dto/response/AdminSearchDto.java
- crm/src/main/java/com/encore/thecatch/admin/repository/AdminQueryRepository.java
- crm/src/main/java/com/encore/thecatch/admin/repository/AdminRepository.java
- crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
- crm/src/main/java/com/encore/thecatch/comments/controller/CommentsController.java
- crm/src/main/java/com/encore/thecatch/comments/dto/request/CreateCommentsReq.java
- crm/src/main/java/com/encore/thecatch/comments/dto/response/CreateCommentsRes.java
- crm/src/main/java/com/encore/thecatch/comments/repository/CommentsRepository.java
- crm/src/main/java/com/encore/thecatch/comments/service/CommentsService.java
- crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
- crm/src/main/java/com/encore/thecatch/complaint/dto/response/MyComplaintRes.java
- crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
- crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
- crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
- crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
- crm/src/main/java/com/encore/thecatch/user/controller/UserController.java
- crm/src/main/java/com/encore/thecatch/user/domain/User.java
- crm/src/main/java/com/encore/thecatch/user/dto/request/UserSearchDto.java
- crm/src/main/java/com/encore/thecatch/user/dto/response/UserInfoDto.java
- crm/src/main/java/com/encore/thecatch/user/dto/response/UserListRes.java
- crm/src/main/java/com/encore/thecatch/user/repository/UserQueryRepository.java
- crm/src/main/java/com/encore/thecatch/user/service/UserService.java
> * #49 
- 고객 검색 로직 구현
- 쿠폰 검색 로직 구현
- 관리자 검색 로직 구현
> [Fix] 검색 로직 구현 및 수정

- crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
- crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
- crm/src/main/java/com/encore/thecatch/common/InitialDataLoader.java
- crm/src/main/java/com/encore/thecatch/user/dto/request/UserSignUpDto.java
> 회사1 어드민 300 유저 300개 초기 데이터 생성

- crm/src/main/java/com/encore/thecatch/complaint/controller/ComplaintController.java
- crm/src/main/java/com/encore/thecatch/complaint/dto/request/UpdateComplaintReq.java
- crm/src/main/java/com/encore/thecatch/complaint/dto/response/DetailComplaintRes.java
- crm/src/main/java/com/encore/thecatch/complaint/dto/response/MyComplaints.java
- crm/src/main/java/com/encore/thecatch/complaint/dto/response/MyPageComplaints.java
- crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
- crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintRepository.java
- crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
> [Fix] 고객페이지 게시글 관련 로직 수정

- crm/src/main/java/com/encore/thecatch/comments/dto/response/DetailCommentRes.java
- crm/src/main/java/com/encore/thecatch/comments/service/CommentsService.java
- crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
- crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
> * #64
> 관리자페이지 문의 글 상세페이지 관련 로직 수정
> [Fix] 관리자페이지 문의 글 상세페이지 관련 로직 수정 (#64)

- crm/src/main/java/com/encore/thecatch/common/firebase/FirebaseConfig.java
- crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
> [fix] 쿠폰검색 로직 수정

- crm/src/main/java/com/encore/thecatch/admin/repository/AdminQueryRepository.java
- crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
- crm/src/main/java/com/encore/thecatch/user/repository/UserQueryRepository.java
> [fix] 검색 기능 로직 수정

- crm/src/main/java/com/encore/thecatch/complaint/dto/response/MyPageComplaints.java
- crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
> [Fix] 마이페이지 게시글 조회 로직 수정

- crm/src/main/java/com/encore/thecatch/admin/repository/AdminQueryRepository.java
- crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
- crm/src/main/java/com/encore/thecatch/common/querydsl/Querydsl4RepositorySupport.java
- crm/src/main/java/com/encore/thecatch/complaint/controller/ComplaintController.java
- crm/src/main/java/com/encore/thecatch/complaint/dto/response/CountCategoryComplaint.java
- crm/src/main/java/com/encore/thecatch/complaint/dto/response/CountStatusComplaintRes.java
- crm/src/main/java/com/encore/thecatch/complaint/dto/response/ListComplaintRes.java
- crm/src/main/java/com/encore/thecatch/complaint/dto/response/MyComplaints.java
- crm/src/main/java/com/encore/thecatch/complaint/dto/response/MyPageComplaints.java
- crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
- crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
- crm/src/main/java/com/encore/thecatch/coupon/repository/CouponQueryRepository.java
- crm/src/main/java/com/encore/thecatch/event/repository/EventQueryRepository.java
- crm/src/main/java/com/encore/thecatch/log/repository/EmailLogQueryRepository.java
- crm/src/main/java/com/encore/thecatch/log/repository/UserLogQueryRepository.java
- crm/src/main/java/com/encore/thecatch/user/dto/request/UserSignUpDto.java
- crm/src/main/java/com/encore/thecatch/user/repository/UserQueryRepository.java
- crm/src/main/java/com/encore/thecatch/user/service/UserService.java
> * #77 
- Querydsl support 제작
- 기존의 queryRepository에 적용
>
> AES와 마스킹 관련해서 저는 최선을 다했다고 생각합니다. 그치만 이상의 더 나은 리팩토링이 있으면 예시와 함께 설명해주시면 수정 고려해보겠습니다.
> [Fix] Query dsl support 제작 (#77)

- crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
- crm/src/main/java/com/encore/thecatch/event/service/EventService.java
- crm/src/main/java/com/encore/thecatch/log/service/LogService.java
- crm/src/main/java/com/encore/thecatch/user/dto/request/UserSignUpDto.java
- crm/src/main/java/com/encore/thecatch/user/service/UserService.java
> [fix] Q객체 오류 수정

- crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
- crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
- crm/src/main/java/com/encore/thecatch/coupon/domain/Coupon.java
- crm/src/main/java/com/encore/thecatch/coupon/domain/CouponStatus.java
- crm/src/main/java/com/encore/thecatch/coupon/dto/CouponReqDto.java
- crm/src/main/java/com/encore/thecatch/coupon/dto/CouponResDto.java
- crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
- crm/src/main/java/com/encore/thecatch/event/controller/EventController.java
- crm/src/main/java/com/encore/thecatch/event/domain/EventStatus.java
- crm/src/main/java/com/encore/thecatch/event/service/EventService.java
- crm/src/main/java/com/encore/thecatch/log/domain/CouponEmailLog.java
- crm/src/main/java/com/encore/thecatch/log/domain/LogType.java
- crm/src/main/java/com/encore/thecatch/log/repository/CouponEmailLogRepository.java
- crm/src/main/java/com/encore/thecatch/mail/service/EmailSendService.java
> ex) #57 
> 상태 수정 및 쿠폰 이메일 로그 추가)
>
> 상태 수정 및 쿠폰 이메일 로그 추가

- crm/src/main/java/com/encore/thecatch/admin/controller/AdminController.java
- crm/src/main/java/com/encore/thecatch/admin/service/AdminService.java
- crm/src/main/java/com/encore/thecatch/comments/service/CommentsService.java
- crm/src/main/java/com/encore/thecatch/common/jwt/JwtAuthFilter.java
- crm/src/main/java/com/encore/thecatch/common/security/SecurityConfig.java
- crm/src/main/java/com/encore/thecatch/mail/dto/CommentsEmailDto.java
- crm/src/main/java/com/encore/thecatch/mail/service/EmailSendService.java
- crm/src/main/resources/application-dev.yml
> [Feat] 슈퍼 계정 관련 로직 추가

- crm/src/main/java/com/encore/thecatch/common/InitialDataLoader.java
> [FIX]initaildata fix

- crm/src/main/java/com/encore/thecatch/common/InitialDataLoader.java
- crm/src/main/java/com/encore/thecatch/complaint/entity/Complaint.java
> [FIX] initail data fix

- batch/src/main/resources/application-dev.yml
> [Fix] Spring batch application.yml 수정

- crm/src/main/java/com/encore/thecatch/common/InitialDataLoader.java
> [FIX]initialData update

- crm/src/main/java/com/encore/thecatch/common/InitialDataLoader.java
> [FIX] initialdata 수정

- crm/src/main/java/com/encore/thecatch/common/InitialDataLoader.java
- crm/src/main/java/com/encore/thecatch/log/domain/UserLog.java
> [fix] init data 수정

- crm/src/main/java/com/encore/thecatch/event/controller/EventController.java
- crm/src/main/java/com/encore/thecatch/event/repository/EventQueryRepository.java
- crm/src/main/java/com/encore/thecatch/event/service/EventService.java
- crm/src/main/java/com/encore/thecatch/log/controller/LogController.java
- crm/src/main/java/com/encore/thecatch/log/repository/EmailLogQueryRepository.java
- crm/src/main/java/com/encore/thecatch/log/service/LogService.java
> 캠페인 차트 로직 구현

- crm/src/main/java/com/encore/thecatch/complaint/dto/request/SearchComplaintCondition.java
- crm/src/main/java/com/encore/thecatch/complaint/dto/response/ListComplaintRes.java
- crm/src/main/java/com/encore/thecatch/complaint/repository/ComplaintQueryRepository.java
- crm/src/main/java/com/encore/thecatch/complaint/service/ComplaintService.java
> 문의글 카테고리 검색 추가

- crm/src/main/java/com/encore/thecatch/common/ResponseCode.java
- crm/src/main/java/com/encore/thecatch/coupon/controller/CouponController.java
- crm/src/main/java/com/encore/thecatch/coupon/service/CouponService.java
- crm/src/main/java/com/encore/thecatch/event/service/EventService.java
> 쿠폰, 캠페인 삭제
